- name: Configure SSH server tunnel
  ansible.builtin.import_tasks:
    file: sshd.yml

- name: Setup UFW to allow SSH tunnel
  ansible.builtin.import_tasks:
    file: ufw.yml

- name: Manage bastion users
  ansible.builtin.import_tasks:
    file: users.yml
