- name: Configure SSH server tunnel
  ansible.builtin.import_tasks:
    file: sshd.yml

- name: Setup UFW to allow SSH tunnel
  ansible.builtin.import_tasks:
    file: ufw.yml
  when: "'ufw' in ansible_facts.packages"

- name: Manage bastion users
  ansible.builtin.import_tasks:
    file: users.yml

# - name: Manage bastion chroot
#   ansible.builtin.import_tasks:
#     file: chroot.yml

# - name: Setup docker container
#   ansible.builtin.import_tasks:
#     file: docker.yml
