- name: Configure SSH server tunnel
  ansible.builtin.template:
    src: tunnel.conf.j2
    dest: /etc/ssh/sshd_config.d/tunnel.conf
    owner: root
    group: root
    mode: 0600
    validate: /usr/sbin/sshd -t -f %s
  notify: Reload sshd

- name: Setup UFW to allow SSH tunnel
  ansible.builtin.import_tasks:
    file: ufw.yml

- name: Create bastion users
  ansible.builtin.import_tasks:
    file: users.yml
