- name: Configure SSH server tunnel
  ansible.builtin.template:
    src: tunnel.conf.j2
    dest: /etc/ssh/sshd_config.d/tunnel.conf
    owner: root
    group: root
    mode: 0600
    validate: /usr/sbin/sshd -t -f %s
  notify: Reload sshd
