# TODO change id_ed25519
- name: Download ssh pub keys
  ansible.builtin.fetch:
    src: "/home/{{ item.name }}/.ssh/id_ed25519.pub"
    dest: credentials/bastion/ssh_pub_keys/{{ item.name }}
    flat: true
  with_items: "{{ users }}"
  when: users
