- name: Ensure rsyslog is installed
  ansible.builtin.package:
    name: rsyslog
    state: latest

- name: Ensure service rsyslog is running and enabled
  ansible.builtin.service:
    name: rsyslog
    state: started
    enabled: true

- name: Configure journald to send logs to rsyslog
  ansible.builtin.template:
    src: journald.conf.j2
    dest: /etc/systemd/journald.conf
    owner: root
    group: root
    mode: 0640
    backup: true
  notify: Restart journald

- name: Configure rsyslog
  ansible.builtin.template:
    src: rsyslog.conf.j2
    dest: /etc/rsyslog.conf
    owner: root
    group: root
    mode: 0640
    backup: true
  notify: Restart rsyslog

# TODO maybe add a check when the rsyslog_server variable is not present so
# that the 00-remote file is removed if the variable is removed
- name: Configure remote rsyslog
  ansible.builtin.template:
    src: rsyslog.d/00-remote.conf.j2
    dest: /etc/rsyslog.d/00-remote.conf
    owner: root
    group: root
    mode: 0640
    backup: true
  when: rsyslog_server_host
  notify: Restart rsyslog

- name: UFW allow rsyslog server out
  ansible.builtin.import_tasks:
    file: ufw.yml
  when: rsyslog_server_host
