- name: Ensure rsyslog is installed
  ansible.builtin.package:
    name: rsyslog
    state: latest

- name: Ensure service rsyslog is running and enabled
  ansible.builtin.service:
    name: rsyslog
    state: started
    enabled: true

- name: Configure rsyslog
  ansible.builtin.template:
    src: rsyslog.conf.j2
    dest: /etc/rsyslog.conf
    owner: root
    group: root
    mode: "0640"
    backup: true
  notify: Restart rsyslog

- name: Configure remote rsyslog
  ansible.builtin.template:
    src: rsyslog.d/00-remote.conf.j2
    dest: /etc/rsyslog.d/00-remote.conf
    owner: root
    group: root
    mode: "0640"
    backup: true
  when: rsyslog_server_host
  notify: Restart rsyslog

- name: Configure rsyslog aggregation server
  ansible.builtin.template:
    src: rsyslog.d/00-aggregator.conf.j2
    dest: /etc/rsyslog.d/00-aggregator.conf
    owner: root
    group: root
    mode: "0640"
    backup: true
  when: rsyslog_enable_udp_reception or rsyslog_enable_tcp_reception
  notify: Restart rsyslog

- name: UFW allow rsyslog server out
  ansible.builtin.import_tasks:
    file: ufw.yml
  when: "'ufw' in ansible_facts.packages"
