---

- name: Common setup
  hosts: all
  become: true

  pre_tasks:
    - name: Load a variable file based on the OS type, or a default if not found.
      ansible.builtin.include_vars: "{{ lookup('ansible.builtin.first_found', params) }}"
      vars:
        params:
          files:
            - "{{ansible_distribution}}.yml"
            - "{{ansible_os_family}}.yml"
            - default.yml
          paths:
            - "vars"
      tags: always

    - name: Debug distribution
      ansible.builtin.debug:
        msg:
          - "{{ ansible_distribution }}"
          - "{{ ansible_os_family }}"
      tags:
        - never
        - get_distrib_infos

  tasks:
    # must be included at the top
    - ansible.builtin.import_role:
        name: shared
      tags: shared

    # use flag setup for a first use of ansible roles
    - ansible.builtin.import_role:
        name: setup
      tags:
        - setup
        - never

    - ansible.builtin.import_role:
        name: ufw
      tags: ufw

    - ansible.builtin.import_role:
        name: apt
      tags: apt

    - ansible.builtin.import_role:
        name: sudo
      tags: sudo

    - ansible.builtin.import_role:
        name: sshd
      tags: sshd

    - ansible.builtin.import_role:
        name: pam
      tags: pam

    - ansible.builtin.import_role:
        name: chrony
      tags: chrony

    - ansible.builtin.import_role:
        name: audit
      tags: audit

    - ansible.builtin.import_role:
        name: sysctl
      tags: sysctl

    - ansible.builtin.import_role:
        name: grub
      tags: grub

    - ansible.builtin.import_role:
        name: sysctl
      tags: sysctl

    - ansible.builtin.import_role:
        name: motd
      tags: motd

    - ansible.builtin.import_role:
        name: cron
      tags: cron

    - ansible.builtin.import_role:
        name: apparmor
      tags: apparmor

    - ansible.builtin.import_role:
        name: rsyslog
      tags: rsyslog

    - ansible.builtin.import_role:
        name: systemd
      tags: systemd

    - ansible.builtin.import_role:
        name: users
      tags: users

    - ansible.builtin.import_role:
        name: network
      tags: network

    - ansible.builtin.import_role:
        name: resolvconf
      tags: resolvconf

  post_tasks:
    - name: Enable UFW
      community.general.ufw:
        state: enabled
      tags: ufw

# Setup low interaction honeypot
- name: Honeypot setup
  hosts: honeypots
  become: true
  roles:
    - role: shared

    - role: suricata
      tags: suricata

    - role: sshd_honeypot
      tags: sshd_honeypot


# Setup apt proxy server
- name: Update server setup
  hosts: update_servers
  become: true
  roles:
    - role: shared

    - role: apt-cacher-ng
      tags: apt-cacher-ng


# Setup SSH tunnel server
- name: Bastion setup
  hosts: bastions
  become: true
  roles:
    - role: shared

    - role: bastion
      tags: bastion

    - role: fail2ban
      tags:
        - fail2ban
        - bastion

    - role: pam_oath
      tags:
        - pam_oath
        - never  # TODO
