---

- name: Common setup
  hosts: all
  become: true
  roles:
    # must be included at the top
    - role: shared

    # should run it only once when installing
    # to avoid removing necessary packages
    # - role: setup
    #   become: true
    #   tags: setup

    - role: ansible
      tags: ansible

    - role: ufw
      tags: ufw

    # setup apt
    - role: apt
      tags: apt

    - role: sudo
      tags: sudo

    - role: sshd
      tags: sshd

    - role: pam
      tags: pam

    - role: chrony
      tags: chrony

    - role: audit
      tags: audit

    - role: sysctl
      tags: sysctl

    - role: grub
      tags: grub

    - role: motd
      tags: motd

    - role: cron
      tags: cron

    - role: apparmor
      tags: apparmor

    - role: rsyslog
      tags: rsyslog

    - role: users
      tags: users

    - role: network
      tags: network

    - role: resolvconf
      tags: resolvconf

  post_tasks:
    - name: Enable UFW
      community.general.ufw:
        state: enabled
      tags: ufw


# Setup low interaction honeypot
- hosts: honeypots
  become: true
  roles:
    - role: shared

    - role: suricata
      tags: suricata

    - role: ssh_honeypot
      tags: ssh_honeypot


# Setup apt proxy server
- hosts: update_servers
  become: true
  roles:
    - role: shared

    - role: apt-cacher-ng
      tags: apt-cacher-ng


# Setup SSH forward server
- hosts: sshd_forward
  become: true
  roles:
    - role: shared

    - role: sshd_forward
      tags: sshd_forward
