---

- name: Common setup
  hosts: all
  become: true

  pre_tasks:
    - name: Load a variable file based on the OS type, or a default if not found.
      ansible.builtin.include_vars: "{{ lookup('ansible.builtin.first_found', params) }}"
      vars:
        params:
          files:
            - "{{ansible_distribution}}.yml"
            - "{{ansible_os_family}}.yml"
            - default.yml
          paths: vars/os
      tags: always

    - name: Debug distribution
      ansible.builtin.debug:
        msg:
          - "{{ ansible_distribution }}"
          - "{{ ansible_os_family }}"
      tags:
        - never
        - get_distrib_infos

  tasks:
    # must be included at the top
    - ansible.builtin.import_role:
        name: shared
      tags: always

    # use flag setup for a first use of ansible roles
    - ansible.builtin.import_role:
        name: setup
      tags:
        - setup
        - never

    - ansible.builtin.import_role:
        name: ufw
      tags:
        - ufw
        - I4

    - ansible.builtin.import_role:
        name: apt
      tags: apt

    - ansible.builtin.import_role:
        name: sudo
      tags:
        - sudo
        - I1

    - ansible.builtin.import_role:
        name: sshd
      tags:
        - sshd
        - I3

    - ansible.builtin.import_role:
        name: pam
      tags:
        - pam
        - I3

    - ansible.builtin.import_role:
        name: chrony
      tags:
        - chrony
        - I2

    - ansible.builtin.import_role:
        name: audit
      tags:
        - audit
        - I1

    - ansible.builtin.import_role:
        name: sysctl
      tags:
        - sysctl
        - I3

    - ansible.builtin.import_role:
        name: grub
      tags:
        - grub
        - I3

    - ansible.builtin.import_role:
        name: motd
      tags:
        - motd
        - I0

    - ansible.builtin.import_role:
        name: cron
      tags:
        - cron
        - I0

    - ansible.builtin.import_role:
        name: apparmor
      tags:
        - apparmor
        - I1

    - ansible.builtin.import_role:
        name: rsyslog
      tags:
        - rsyslog
        - I0

    - ansible.builtin.import_role:
        name: systemd
      tags:
        - systemd
        - I0

    - ansible.builtin.import_role:
        name: users
      tags:
        - users
        - I1

    - ansible.builtin.import_role:
        name: network
      tags:
        - network
        - I1

    - ansible.builtin.import_role:
        name: resolvconf
      tags:
        - resolvconf
        - I2

    - ansible.builtin.import_role:
        name: logrotate
      tags:
        - logrotate
        - I0

    - ansible.builtin.import_role:
        name: aide
      tags:
        - aide
        - I2

  post_tasks:
    - name: Enable UFW
      community.general.ufw:
        state: enabled
        logging: medium
      tags:
        - ufw
        - I4


# Setup apt proxy server
- name: Update server setup
  hosts: update_servers
  become: true
  tasks:
    - ansible.builtin.import_role:
        name: shared
      tags: always

    - ansible.builtin.import_role:
        name: apt-cacher-ng
      tags: apt-cacher-ng


# Setup SSH tunnel server
- name: Bastion setup
  hosts: bastions
  become: true
  tasks:
    - ansible.builtin.import_role:
        name: shared
      tags: always

    - ansible.builtin.import_role:
        name: bastion
      tags: bastion

    - ansible.builtin.import_role:
        name: fail2ban
      tags:
        - fail2ban
        - bastion

    - ansible.builtin.import_role:
        name: suricata
      tags:
        - suricata
        - bastion

    - ansible.builtin.import_role:
        name: pam_oath
      tags:
        - pam_oath
        - never  # TODO finish pam_oath and remove this


# Setup low interaction honeypot
- name: Honeypot setup
  hosts: honeypots
  become: true
  tasks:
    - ansible.builtin.import_role:
        name: shared
      tags: always

    - ansible.builtin.import_role:
        name: suricata
      tags: suricata

    - ansible.builtin.import_role:
        name: sshd_honeypot
      tags: sshd_honeypot
