- name: Configure honeypot
  hosts:
    - honey
    - honey_master
  tasks:
    - name: Install suricata
      ansible.builtin.package:
        name:
          - suricata
        state: latest
      become: true
    - name: Configure suricata
      ansible.builtin.copy:
        src: config/suricata.yaml
        dest: /etc/suricata/suricata.yaml
        owner: root
        group: root
        mode: 0644
        backup: true
      become: true
      notify:
        - Reload suricata
    - name: Ensure the suricata is running and enabled
      ansible.builtin.service:
        name: suricata
        state: started
        enabled: true
      become: true
    - name: Suricata update cron job
      ansible.builtin.cron:
        name: suricata update
        hour: 3
        minute: 30
        job: suricata-update
      become: true
    - name: Configure UFW
      import_tasks: tasks/ufw.yml
      become: true

  handlers:
    - name: Reload suricata
      become: true
      ansible.builtin.service:
        name: suricata
        state: reloaded
