- name: Install aide
  ansible.builtin.package:
    name: aide
    state: latest
  notify:
    - Initialize aide database

- name: Creates disabled aide rules directory
  ansible.builtin.file:
    path: /etc/aide/aide.conf.d.disabled/
    state: directory

- name: Get list of aide rules to disable
  ansible.builtin.stat:
    path: "/etc/aide/aide.conf.d/{{ item }}"
  loop: "{{ aide_remove_rules }}"
  register: aide_remove_rules_stat

- name: Move disabled aide rules to aide.conf.d.disabled
  ansible.builtin.copy:
    src: "/etc/aide/aide.conf.d/{{ item }}"
    dest: "/etc/aide/aide.conf.d.disabled/{{ item }}"
    remote_src: true
  loop: "{{ \
      aide_remove_rules_stat.results | \
      selectattr('stat.exists', 'equalto', true) | \
       map(attribute='item') \
  }}"

- name: Remove disabled aide rules from aide.conf.d
  ansible.builtin.file:
    path: "/etc/aide/aide.conf.d/{{ item }}"
    state: absent
  loop: "{{ aide_remove_rules }}"

- name: Schedule aide check
  ansible.builtin.cron:
    name: aide check
    job: /usr/bin/aide --config /etc/aide/aide.conf --check
    special_time: daily
