# required for apt to connect to remote repository
# TODO this is not very clean at all ! but we can't filter by domain name and
# we also can't hardcode the IP of debian servers because they might change
# the best thing to do is to have a transparent proxy to the internet that will
# filter domain names
- name: UFW allow HTTP out for apt
  community.general.ufw:
    rule: allow
    port: http
    direction: out
    comment: HTTP out for apt
  when: "'ufw' in ansible_facts.packages"
