- name: Configure apt
  ansible.builtin.template:
    src: 00aptproxy.j2
    dest: /etc/apt/apt.conf.d/00aptproxy
    owner: root
    group: root
    mode: "0644"

- name: UFW allow apt proxy server
  community.general.ufw:
    rule: allow
    port: "{{ apt_proxy_port }}"
    proto: tcp
    direction: out
    to_ip: "{{ apt_proxy_addr }}"
    comment: apt proxy
