- name: Gather the package facts
  ansible.builtin.package_facts:

- name: Security mitigation for CVE-2023-22809
  # CVE-2023-22809
  # Versions 1.8.0 through 1.9.12p1 are affected
  when: "'sudo' in ansible_facts.packages"
  tags:
    - CVE-2023-22809
  block:
    - name: Get sudo version
      ansible.builtin.set_fact:
        sudo_verison: "{{ ansible_facts.packages['sudo'][0].version }}"

    - name: Check if vulnerable sudo version
      ansible.builtin.set_fact:
        sudo_vuln_cve: "{{ sudo_verison is regex('^1\\.(8\\.|9\\.([0-9][^\\d]|1[0-1])|9\\.12p1).*') }}"

    - name: Message if sudo is vulnerable to CVE-2023-22809
      ansible.builtin.debug:
        msg: "Sudo version {{ sudo_verison }} vulnerable to CVE-2023-22809 !!"
      when: sudo_vuln_cve

    - name: Security mitigation for CVE-2023-22809
      ansible.builtin.template:
        src: sudoers.d/cve-2023-22809.j2
        dest: /etc/sudoers.d/cve-2023-22809
        owner: root
        group: root
        mode: "0644"
      # sudo version 1.8.0 to 1.9.12p1
      when: sudo_vuln_cve

    - name: Check if CVE-2023-22809 is mitigated and not needed
      ansible.builtin.stat:
        dest: /etc/sudoers.d/cve-2023-22809
      register: sudo_cve_patched
      when: not sudo_vuln_cve

    - name: Message if not needing mitigation anymore
      ansible.builtin.debug:
        msg: "Sudo version {{ sudo_verison }} is safe, removing mitigation !"
      when:
        - not sudo_vuln_cve
        - sudo_cve_patched.stat.exists

    - name: Remove CVE-2023-22809 mitigation because sudo is patched
      ansible.builtin.file:
        path: /etc/sudoers.d/cve-2023-22809
        state: absent
      when:
        - not sudo_vuln_cve
        - sudo_cve_patched.stat.exists
