- name: Install cron
  ansible.builtin.package:
    name: cron
    state: latest

- name: Ensure cron is running and enabled
  ansible.builtin.service:
    name: "{{ cron_service | d('cron') }}"
    state: started
    enabled: true

- name: Ensure permissions on /etc/crontab are configured
  ansible.builtin.file:
    path: /etc/crontab
    state: file
    owner: root
    group: root
    mode: 0600
  with_first_found:
    - files:
        - /etc/crontab
      skip: true

- name: Ensure permissions on /etc/cron.* are configured
  ansible.builtin.file:
    path: "/etc/cron.{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0700
  with_items:
    - d
    - hourly
    - daily
    - weekly
    - monthly
