# TODO remove files in /etc/update-motd.d/
# or add our and remove the 10-uname file

- name: Ensure motd are configured
  ansible.builtin.copy:
    src: motd
    dest: "{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - /etc/motd
    - /etc/issue
    - /etc/issue.net
