- name: Ensure motd are configured
  ansible.builtin.copy:
    dest: "{{ item }}"
    content: "{{ motd_content }}\n\n"
    owner: root
    group: root
    mode: 0644
  with_items:
    - /etc/motd
    - /etc/issue
    - /etc/issue.net
