- name: Install suricata
  ansible.builtin.package:
    name:
      - suricata
    state: latest

- name: Configure suricata
  ansible.builtin.copy:
    src: suricata.yaml
    dest: /etc/suricata/suricata.yaml
    owner: root
    group: root
    mode: 0644
    backup: true
  notify:
    - Reload suricata

- name: Add suricata custom rules
  ansible.builtin.template:
    src: custom.rules.j2
    dest: /var/lib/suricata/rules/custom.rules
    owner: root
    group: root
    mode: 0644
    backup: true
  notify:
    - Reload suricata

- name: Ensure suricata is running and enabled
  ansible.builtin.service:
    name: suricata
    state: started
    enabled: true

- name: Suricata update cron job
  ansible.builtin.cron:
    name: suricata update
    hour: 3
    minute: 30
    job: suricata-update
  notify:
    - Suricata update rules
