- name: Disable IPv6
  ansible.builtin.replace:
    dest: /etc/default/grub
    regexp: '^(GRUB_CMDLINE_LINUX=(?!.*ipv6.disable)\"[^\"]*)(\".*)'
    replace: '\1 ipv6.disable=1\2'
  when: grub_disable_ipv6
  notify:
    - Update GRUB
    - Reboot
