- name: Ensure apparmor is installed
  ansible.builtin.package:
    name: apparmor
    state: latest

- name: Ensure apparmor-utils is installed
  ansible.builtin.package:
    name: apparmor-utils
    state: latest

- name: Import apparmor GRUB tasks
  ansible.builtin.import_tasks:
    file: grub.yml
