- name: Ensure apparmor and apparmor-utils are installed
  ansible.builtin.package:
    name:
      - apparmor
      - apparmor-utils
    state: latest

- name: Import apparmor GRUB tasks
  ansible.builtin.import_tasks:
    file: grub.yml
