- name: UFW allow loopback interface in
  community.general.ufw:
    rule: allow
    interface: lo
    direction: in
    comment: lo interface allow in

- name: UFW allow loopback interface out
  community.general.ufw:
    rule: allow
    interface: lo
    direction: out
    comment: lo interface allow out

- name: UFW deny 127.0.0.0/8 in
  community.general.ufw:
    rule: deny
    src: 127.0.0.0/8
    direction: in
    comment: 127/8 deny in

# IPv6 is disabled
# - name: UFW deny ::1 in
#   community.general.ufw:
#     rule: deny
#     src: '::1'
#     direction: in
#     comment: loopback
