- name: UFW allow apt proxy server in
  community.general.ufw:
    rule: allow
    port: "{{ apt_cacher_ng_port }}"
    proto: tcp
    direction: in
    from_ip: "{{ item }}"
    comment: apt proxy server
  with_items: "{{ apt_cacher_ng_from_ip }}"
