- name: Configure login.defs
  ansible.builtin.template:
    src: login.defs.j2
    dest: /etc/login.defs
    owner: root
    group: root
    mode: 0644
    backup: true

- name: Configure useradd default
  ansible.builtin.template:
    src: useradd.j2
    dest: /etc/default/useradd
    owner: root
    group: root
    mode: 0644
    backup: true

- name: Add users
  ansible.builtin.user:
    name: "{{ item.name }}"
    comment: "{{ item.comment | default('') }}"
    password: "{{ lookup('password', 'credentials/' + item.name + '/password.txt encrypt=md5_crypt') }}"
    uid: "{{ item.uid }}"
    shell: /bin/bash
    password_expire_max: 30
    update_password: on_create
    remove: "{{ item.remove | default(false) }}"  # remove home if the user is deleted
    state: "{{ item.state | default('present') }}"  # to remove an account set state to 'absent'
    expires: "{{ item.expires | default(-1) }}"
  with_items: "{{ users }}"
  register: updated_users
  notify: "updated users"
  when: users

- name: Configure shell timeout
  ansible.builtin.template:
    src: autologout.sh.j2
    dest: /etc/profile.d/autologout.sh
    owner: root
    group: root
    mode: 0644

- name: Add SSH authorized_keys
  ansible.builtin.import_tasks:
    file: ssh.yml
