- name: Ensure .ssh folders exist
  ansible.builtin.file:
    path: "/home/{{ item.name }}/.ssh"
    state: directory
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: 0700
  with_items: "{{ users }}"
  ignore_errors: true
  when: users

- name: Create authorized_keys to enable ssh
  ansible.builtin.copy:
    dest: "/home/{{ item.name }}/.ssh/authorized_keys"
    content: "{{ item.authorized_keys }}\n"
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: 0600
    backup: true
  with_items: "{{ users }}"
  ignore_errors: true
  when: users
