- name: Create authorized_keys to enable ssh
  ansible.builtin.copy:
    src: "users/{{ item }}/authorized_keys"
    dest: "/home/{{ item }}/.ssh/"
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: 0600
    backup: true
  loop: "{{ \
         updated_users.results | \
         selectattr('state', 'equalto', 'present') | \
         map(attribute='item') | \
         map(attribute='name') | \
         list \
  }}"
  ignore_errors: true
  when: users
