# There is a module to manage sysctl
# https://docs.ansible.com/ansible/latest/collections/ansible/posix/sysctl_module.html#ansible-collections-ansible-posix-sysctl-module

- name: Configure sysctl
  ansible.builtin.template:
    src: sysctl.conf.j2
    dest: /etc/sysctl.conf
    owner: root
    group: root
    mode: 0644
    backup: true
  notify: Reboot

- name: Add sysctl configs
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/etc/sysctl.d/{{ item | basename | regex_replace('\\.j2$', '') }}"
    owner: root
    group: root
    mode: 0644
    backup: true
  with_fileglob:
    - templates/sysctl.d/*.j2
  notify: Reboot
