- name: Expire passwords
  ansible.builtin.command:
    cmd: "passwd --expire {{ item.name }}"
  with_items: "{{ \
         users | \
         selectattr('expire_password', 'defined') | \
         selectattr('expire_password', 'equalto', true) \
  }}"
  listen: expire_passwords
