- name: Users handlers
  ansible.builtin.import_tasks: users.yml

- name: Sysctl handlers
  ansible.builtin.import_tasks: sysctl.yml

# reboot last
- name: System handlers
  ansible.builtin.import_tasks: system.yml
