- name: Chrony handlers
  ansible.builtin.import_tasks: chrony.yml

- name: Users handlers
  ansible.builtin.import_tasks: users.yml

- name: Rsyslog handlers
  ansible.builtin.import_tasks: rsyslog.yml

- name: Audit handlers
  ansible.builtin.import_tasks: audit.yml

- name: GRUB handlers
  ansible.builtin.import_tasks: grub.yml

- name: Sysctl handlers
  ansible.builtin.import_tasks: sysctl.yml

- name: SSH handlers
  ansible.builtin.import_tasks: ssh.yml

# reboot last
- name: System handlers
  ansible.builtin.import_tasks: system.yml
