- name: Add Ansible user
  ansible.builtin.user:
    name: ansible
    comment: Ansible management account
    password: "{{ lookup('password', 'credentials/ansible/' + ansible_host + ' encrypt=md5_crypt') }}"
    shell: /bin/bash
    update_password: always
    home: /home/ansible
  notify: Ansible message

- name: Ensure ansible .ssh folder exist
  ansible.builtin.file:
    path: /home/ansible/.ssh
    state: directory
    owner: ansible
    group: ansible
    mode: 0700

- name: Create ansible authorized_keys to enable ssh
  ansible.builtin.copy:
    dest: /home/ansible/.ssh/authorized_keys
    content: "{{ ansible_authorized_keys }}\n"
    owner: ansible
    group: ansible
    mode: 0600
  when: ansible_authorized_keys
