- name: Add sudo lecture message
  ansible.builtin.copy:
    content: "{{ sudo_lecture }}\n"
    dest: /usr/share/doc/sudo_lecture.txt
    owner: root
    group: root
    mode: "0644"

- name: Configure sudo lecture
  ansible.builtin.template:
    src: sudoers.d/lecture.j2
    dest: /etc/sudoers.d/lecture
    owner: root
    group: root
    mode: "0440"
    backup: true
    validate: '/usr/sbin/visudo -cf %s'
