- name: Ensure sudo is installed
  ansible.builtin.package:
    name: sudo
    state: latest

- name: Ensure group sudo exists
  ansible.builtin.group:
    name: "{{ sudo_group_name }}"
    gid: "{{ sudo_group_gid | default(omit) }}"
    state: present

- name: Restrict permissions for sudo executable
  ansible.builtin.file:
    path: /usr/bin/sudo
    owner: root
    group: "{{ sudo_group_name }}"
    mode: u=rws,g=rx,o-rwx

- name: Add users to sudo group
  ansible.builtin.user:
    name: "{{ item }}"
    groups: "{{ sudo_group_name }}"
    append: true
  with_items: "{{ sudo_users }}"
  when: sudo_users
  notify: Reboot

- name: Configure sudo
  ansible.builtin.template:
    src: sudoers.j2
    dest: /etc/sudoers
    owner: root
    group: root
    mode: "0440"
    backup: true
    validate: '/usr/sbin/visudo -cf %s'

- name: Ensure sudo config folder exists
  ansible.builtin.file:
    path: /etc/sudoers.d
    state: directory
    mode: "0755"

- name: Configure sudo lecture
  ansible.builtin.import_tasks:
    file: lecture.yml
  when: sudo_custom_lecture
