- name: Install fail2ban
  ansible.builtin.package:
    name: fail2ban
    state: latest

- name: Configure fail2ban
  ansible.builtin.template:
    src: fail2ban.local.j2
    dest: /etc/fail2ban/fail2ban.local
    owner: root
    group: root
    mode: "0644"
    backup: true
  notify: Restart fail2ban

- name: Configure fail2ban jails
  ansible.builtin.template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: "0644"
    backup: true
  notify: Restart fail2ban

- name: Ensure the fail2ban service is running and enabled
  ansible.builtin.service:
    name: fail2ban
    state: started
    enabled: true
