- name: Install fail2ban
  ansible.builtin.package:
    name: fail2ban
    state: latest

- name: Ensure the fail2ban service is running and enabled
  ansible.builtin.service:
    name: fail2ban
    state: started
    enabled: true

- name: Configure fail2ban
  ansible.builtin.template:
    src: jail.conf.j2
    dest: /etc/fail2ban/jail.conf
    owner: root
    group: root
    mode: 0644
    backup: true
