- name: Install auditd
  ansible.builtin.package:
    name:
      - auditd
    state: latest
  become: true

- name: Ensure auditd is running and enabled
  ansible.builtin.service:
    name: auditd
    state: started
    enabled: true
  become: true

- name: Add auditd rules
  ansible.builtin.copy:
    src: audit.rules
    dest: /etc/audit/rules.d/
    owner: root
    group: root
    mode: 0644
    backup: true
  become: true
  notify: Reload auditd
