- name: Ensure audit is installed
  ansible.builtin.package:
    name: auditd
    state: latest

- name: Ensure audit is running and enabled
  ansible.builtin.service:
    name: auditd
    state: started
    enabled: true

- name: Add audit rules
  ansible.builtin.template:
    src: audit.rules.j2
    dest: /etc/audit/rules.d/
    owner: root
    group: root
    mode: 0644
    backup: true
  notify: Reboot
