- name: Install cron
  ansible.builtin.package:
    name: cron
    state: latest

- name: Ensure cron is running and enabled
  ansible.builtin.service:
    name: cron
    state: started
    enabled: true
