- name: Configure GRUB
  ansible.builtin.template:
    src: grub.j2
    dest: /etc/default/grub
    owner: root
    group: root
    mode: 0600
    backup: true
  notify:
    - Update GRUB
    - Reboot
