- name: Users tasks
  ansible.builtin.import_tasks: users.yml

#- name: Sysctl tasks
#  ansible.builtin.import_tasks: sysctl.yml
#  when: ansible_virtualization_role != "guest" or ansible_virtualization_type != "docker"

- name: PAM tasks
  ansible.builtin.import_tasks: pam.yml

- name: MOTD tasks
  ansible.builtin.import_tasks: motd.yml

#- name: Sudo tasks
#  ansible.builtin.import_tasks: sudo.yml

#- name: Audit tasks
#  ansible.builtin.import_tasks: audit.yml

#- name: rsyslog tasks
#  ansible.builtin.import_tasks: rsyslog.yml
#  when: ansible_virtualization_role != "guest" or ansible_virtualization_type != "docker"

#- name: NTP
#  ansible.builtin.import_tasks: ntp.yml

#- name: Cron tasks
#  ansible.builtin.import_tasks: cron.yml

- name: UFW tasks
  ansible.builtin.import_tasks: ufw.yml
  when: ansible_virtualization_role != "guest" or ansible_virtualization_type != "docker"
