- name: SSHD tasks
  import_tasks: sshd.yml

- name: Users tasks
  import_tasks: users.yml

- name: Sysctl tasks
  import_tasks: sysctl.yml

- name: PAM tasks
  import_tasks: pam.yml

- name: Cron tasks
  import_tasks: cron.yml

#- name: UFW tasks
#  import_tasks: ufw.yml
