- name: Ansible
  ansible.builtin.import_tasks: ansible.yml
  tags: ansible

- name: SSH tasks
  ansible.builtin.import_tasks: ssh.yml
  tags: ssh

- name: Users tasks
  ansible.builtin.import_tasks: users.yml
  tags: users

- name: SSH users tasks
  ansible.builtin.import_tasks: ssh_users.yml
  tags: ssh_users

# configure IF GRUB is installed
- name: GRUB tasks
  ansible.builtin.import_tasks: grub.yml
  when: ansible_virtualization_role != "guest" or ansible_virtualization_type != "docker"
  tags: grub

- name: Sysctl tasks
  ansible.builtin.import_tasks: sysctl.yml
  when: ansible_virtualization_role != "guest" or ansible_virtualization_type != "docker"
  tags: sysctl

- name: PAM tasks
  ansible.builtin.import_tasks: pam.yml
  tags: pam

- name: MOTD tasks
  ansible.builtin.import_tasks: motd.yml
  tags: motd

- name: Sudo tasks
  ansible.builtin.import_tasks: sudo.yml
  tags: sudo

- name: Audit tasks
  ansible.builtin.import_tasks: audit.yml
  tags: audit

- name: Rsyslog tasks
  ansible.builtin.import_tasks: rsyslog.yml
  when: ansible_virtualization_role != "guest" or ansible_virtualization_type != "docker"
  tags: rsyslog

- name: NTP
  ansible.builtin.import_tasks: ntp.yml
  tags: ntp

- name: Cron tasks
  ansible.builtin.import_tasks: cron.yml
  tags: cron

- name: UFW tasks
  ansible.builtin.import_tasks: ufw.yml
  when: ansible_virtualization_role != "guest" or ansible_virtualization_type != "docker"
  tags: ufw

- name: AppArmor tasks
  ansible.builtin.import_tasks: apparmor.yml
  tags: apparmor
