- name: SSHD tasks
  import_tasks: sshd.yml

- name: Users tasks
  import_tasks: users.yml

- name: Cron tasks
  import_tasks: cron.yml

- name: Suricata tasks
  import_tasks: suricata.yml

- name: UFW tasks
  import_tasks: ufw.yml
