- name: Install
  ansible.builtin.import_tasks: install.yml

- name: SSHD tasks
  ansible.builtin.import_tasks: sshd.yml

- name: Users tasks
  ansible.builtin.import_tasks: users.yml

- name: Sysctl tasks
  ansible.builtin.import_tasks: sysctl.yml

- name: PAM tasks
  ansible.builtin.import_tasks: pam.yml

- name: Sudo tasks
  ansible.builtin.import_tasks: sudo.yml

- name: Auditd tasks
  ansible.builtin.import_tasks: auditd.yml

- name: Cron tasks
  ansible.builtin.import_tasks: cron.yml

- name: UFW tasks
  ansible.builtin.import_tasks: ufw.yml
