- name: Configure libpam
  # packages have different names on other distribs, it's hard to keep tracks
  # of all of them, it works for Debian now, we filter to avoid errors
  when: ansible_distribution=='Debian'
  block:
    - name: Ensure libcrack is installed
      ansible.builtin.package:
        name: libpam-pwquality
        state: latest

    - name: Configure login.defs
      ansible.builtin.copy:
        src: login.defs
        dest: /etc/login.defs
        owner: root
        group: root
        mode: 0644
        backup: true

    - name: Add password user doc
      ansible.builtin.copy:
        src: good-password.txt
        dest: /usr/share/doc/
        owner: root
        group: root
        mode: 0644
        backup: true

    # ANSSI-PB-028: R31 - Utiliser des mots de passe robustes
    - name: Configure common-password
      ansible.builtin.template:
        src: common-password.j2
        dest: /etc/pam.d/common-password
        owner: root
        group: root
        mode: 0644
        backup: true

    # ANSSI-PB-028: R31 - Utiliser des mots de passe robustes
    # - name: Add strong password requirements
    #   community.general.pamd:
    #     name: common-password
    #     new_type: password
    #     new_control: requisite
    #     new_module_path: pam_pwquality.so
    #     module_arguments: 'retry=3
    #       minlen=12
    #       dcredit=0
    #       ucredit=-1
    #       lcredit=-1
    #       ocredit=-1
    #       maxrepeat=1
    #       maxsequence=1
    #       gecoscheck
    #       reject_username
    #       enforce_for_root'
    #     state: before
    #     type: password
    #     control: requisite
    #     module_path: pam_deny.so
    #     backup: true
