- name: Install libcrack
  ansible.builtin.package:
    name:
      - libpam-cracklib
    state: latest

- name: Configure login.defs
  ansible.builtin.copy:
    src: login.defs
    dest: /etc/login.defs
    owner: root
    group: root
    mode: 0644
    backup: true

- name: Add password user doc
  ansible.builtin.copy:
    src: good-password.txt
    dest: /usr/share/doc/
    owner: root
    group: root
    mode: 0644
    backup: true

- name: Configure common-password
  ansible.builtin.copy:
    src: common-password
    dest: /etc/pam.d/common-password
    owner: root
    group: root
    mode: 0644
    backup: true

# when we install libcrack it will update common-password so we could directly
# edit it with the ansible package, but imo it's better to change the file and
# be absolutely certain that it's taken into account
# - name: Add strong password requirements
#   community.general.pamd:
#     name: common-password
#     type: password
#     control: requisite
#     module_path: pam_cracklib.so
#     module_arguments: 'retry=3
#       minlen=12
#       minclass=3
#       dcredit=0
#       ucredit=-1
#       lcredit=-1
#       ocredit=-1
#       maxrepeat=1
#       maxsequence=1
#       gecoscheck
#       reject_username
#       enforce_for_root'
#     backup: true
