- name: Ensure rsyslog is installed
  ansible.builtin.package:
    name: rsyslog
    state: latest

- name: Ensure service rsyslog is running and enabled
  ansible.builtin.service:
    name: rsyslog
    state: started
    enabled: true
