- name: Install OpenSSH server
  ansible.builtin.package:
    name: openssh-server
    state: latest
  notify: Reload sshd

- name: Ensure group ssh exists
  ansible.builtin.group:
    name: "{{ ssh_group_name }}"
    gid: "{{ ssh_group_gid }}"

- name: Add ansible user to ssh group
  ansible.builtin.user:
    name: ansible
    groups: "{{ ssh_group_name }}"
    append: true

- name: Configure SSH
  ansible.builtin.template:
    src: etc/ssh/sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0600
    validate: /usr/sbin/sshd -t -f %s
    backup: true
  notify: Reload sshd

- name: Create SSH config folder
  ansible.builtin.file:
    path: /etc/ssh/sshd_config.d
    state: directory
    mode: 0755
