- name: Ensure group ssh group exists with correct gid
  ansible.builtin.group:
    name: sshusers
    gid: '{{ ssh_group_gid }}'
  become: true

- name: Configure SSHD
  ansible.builtin.template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0600
    validate: /usr/sbin/sshd -t -f %s
    backup: true
  become: true
  notify: Reload sshd
