- name: Ensure group sudo exists
  ansible.builtin.group:
    name: sudo
    state: present

- name: Restrict permissions for sudo executable
  ansible.builtin.file:
    path: /usr/bin/sudo
    owner: root
    group: sudo
    mode: u=rws,g=rx,o-rwx

- name: Add Ansible user to sudo group
  ansible.builtin.user:
    name: ansible
    groups: sudo
    append: true
  notify: Reboot

# TODO make a list of sudo users
- name: Add users to sudo group
  ansible.builtin.user:
    name: "{{ item.name }}"
    groups: sudo
    append: true
  with_items: "{{ users }}"
  when: users
  notify: Reboot

- name: Configure sudo
  ansible.builtin.template:
    src: etc/sudoers.j2
    dest: /etc/sudoers
    owner: root
    group: root
    mode: 0440
    backup: true

- name: Create sudo config folder
  ansible.builtin.file:
    path: /etc/sudoers.d
    state: directory
    mode: 0755
