- name: Configure sysctl
  ansible.builtin.template:
    src: sysctl.conf.j2
    dest: /etc/sysctl.conf
    owner: root
    group: root
    mode: 0644
    backup: true
  become: true
  notify:
    - Reload sysctl
