# There is a module to manage sysctl
# https://docs.ansible.com/ansible/latest/collections/ansible/posix/sysctl_module.html#ansible-collections-ansible-posix-sysctl-module

# R22,R23,R24,R25 - Paramétrage des sysctl réseau
- name: Configure sysctl
  ansible.builtin.template:
    src: sysctl.conf.j2
    dest: /etc/sysctl.conf
    owner: root
    group: root
    mode: 0644
    backup: true
  become: true
  notify:
    - Reload sysctl
