- name: Install UFW
  ansible.builtin.package:
    name: ufw
    state: latest

- name: Ensure the UFW service is running and enabled
  ansible.builtin.service:
    name: ufw
    state: started
    enabled: true

- name: Enable UFW and set logging level
  community.general.ufw:
    logging: medium

- name: UFW allow SSH
  community.general.ufw:
    rule: limit
    port: "{{ ansible_port }}"
    proto: tcp
    direction: in
    comment: SSH

- name: UFW default deny outgoing
  community.general.ufw:
    policy: deny
    direction: outgoing

- name: UFW default deny incoming
  community.general.ufw:
    policy: deny
    direction: incoming

- name: UFW default deny routed
  community.general.ufw:
    policy: deny
    direction: routed

- name: UFW allow loopback in
  community.general.ufw:
    rule: allow
    interface: lo
    direction: in
    comment: loopback interface

- name: UFW allow loopback out
  community.general.ufw:
    rule: allow
    interface: lo
    direction: out
    comment: loopback interface

- name: UFW deny 127.0.0.0/8 in
  community.general.ufw:
    rule: deny
    src: 127.0.0.0/8
    direction: in
    comment: loopback

# IPv6 is disabled
# - name: UFW deny ::1 in
#   community.general.ufw:
#     rule: deny
#     src: '::1'
#     direction: in
#     comment: 'loopback'

- name: UFW allow out 53
  community.general.ufw:
    rule: allow
    port: 53
    direction: out
    comment: DNS

# required for apt to connect to remote repository
- name: UFW allow HTTP out for apt
  community.general.ufw:
    rule: allow
    port: http
    direction: out
    comment: HTTP out for apt

- name: UFW allow NTP out
  community.general.ufw:
    rule: allow
    port: 123
    proto: udp
    direction: out
    comment: NTP

- name: Enable UFW
  community.general.ufw:
    state: enabled
