- name: Add users
  ansible.builtin.user:
    name: '{{ item.name }}'
    comment: "{{ item.comment | default('') }}"
    password: "{{ lookup('password', 'credentials/' + item.name + '/password.txt encrypt=md5_crypt') }}"
    uid: '{{ item.uid }}'
    groups: sudo,sshusers
    shell: /bin/bash
    password_expire_max: 30
    update_password: on_create
    remove: '{{ item.remove | default(false) }}'  # remove home if the user is deleted
    state: "{{ item.state | default('present') }}"  # to remove an account set state to 'absent'
    expires: "{{ item.expires | default(-1) }}"
  with_items: '{{ users }}'
  become: true
  register: updated_users
  notify: "updated users"
  when: users

- name: Create authorized_keys to enable ssh
  ansible.builtin.copy:
    src: 'users/{{ item }}/authorized_keys'
    dest: '/home/{{ item }}/.ssh/'
    owner: '{{ item }}'
    group: '{{ item }}'
    mode: 0600
    backup: true
  loop: "{{ updated_users.results | selectattr('state', 'equalto', 'present') | map(attribute='item') | map(attribute='name') | list }}"
  ignore_errors: true
  become: true
  when: users
