- name: Run apt-get update
  ansible.builtin.apt:
    update_cache: true
  when: ansible_distribution=='Debian'

- name: Ensure security patches are up to date
  ansible.builtin.package:
    name: "*"
    state: latest
  register: updated_packages
