- name: Ensure Telnet is uninstalled
  ansible.builtin.package:
    name: telnet
    state: absent

- name: Ensure Sendmail is uninstalled
  ansible.builtin.package:
    name: sendmail
    state: absent

- name: Ensure prelink is uninstalled
  ansible.builtin.package:
    name: prelink
    state: absent

- name: Ensure talk is uninstalled
  ansible.builtin.package:
    name: talk
    state: absent

- name: Ensure LDAP client is uninstalled
  ansible.builtin.package:
    name: ldap-utils
    state: absent
