- name: Ensure audit is installed
  ansible.builtin.package:
    name:
      - auditd
      - audispd-plugins
    state: latest

- name: Ensure audit is running and enabled
  ansible.builtin.service:
    name: auditd
    state: started
    enabled: true

- name: Configure audit
  ansible.builtin.template:
    src: auditd.conf.j2
    dest: /etc/audit/auditd.conf
    owner: root
    group: root
    mode: "0640"
    backup: true
  notify: Reboot

- name: Add audit rules
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/etc/audit/rules.d/{{ item | basename | regex_replace('\\.j2$', '') }}"
    owner: root
    group: root
    mode: "0640"
  with_fileglob:
    - templates/rules.d/*.j2
  notify:
    - Merge auditd configuration
    - Reboot

- name: Import audit GRUB tasks
  ansible.builtin.import_tasks:
    file: grub.yml
