- name: Install squid
  ansible.builtin.package:
    name: squid
    state: latest

- name: Ensure squid is running and enabled
  ansible.builtin.service:
    name: squid
    state: started
    enabled: true

- name: Configure squid
  ansible.builtin.template:
    src: squid.conf.j2
    dest: /etc/squid/squid.conf
    owner: root
    group: root
    mode: "0644"
    backup: true
  notify: Reload squid

- name: Add squid configurations
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/etc/squid/conf.d/{{ item | basename | regex_replace('\\.j2$', '') }}"
    owner: root
    group: root
    mode: "0644"
    backup: false  # leaving old files can cause the config to be invalid
  with_fileglob:
    - templates/conf.d/*.j2
  notify: Reload squid

- name: Add squid domain blacklist
  ansible.builtin.template:
    src: domain_blacklist.txt.j2
    dest: /etc/squid/domain_blacklist.txt
    owner: root
    group: root
    mode: "0644"
  notify: Reload squid  # TODO check if this is needed or not

- name: Add squid domain whitelist
  ansible.builtin.template:
    src: domain_whitelist.txt.j2
    dest: /etc/squid/domain_whitelist.txt
    owner: root
    group: root
    mode: "0644"
  notify: Reload squid  # TODO check if this is needed or not

- name: UFW tasks
  ansible.builtin.import_tasks: ufw.yml
