- name: UFW allow HTTP proxy server
  community.general.ufw:
    rule: allow
    port: "{{ squid_http_port }}"
    proto: tcp
    direction: in
    comment: HTTP proxy

- name: UFW allow HTTP out proxy server
  community.general.ufw:
    rule: allow
    port: 80
    proto: tcp
    direction: out
    comment: HTTP out squid proxy

- name: UFW allow HTTPS out proxy server
  community.general.ufw:
    rule: allow
    port: 443
    proto: tcp
    direction: out
    comment: HTTPS out squid proxy
