- name: Ensure OpenSSH server is installed
  ansible.builtin.package:
    name: openssh-server
    state: latest

- name: Ensure SSH group exists
  ansible.builtin.group:
    name: "{{ sshd_group_name }}"
    gid: "{{ sshd_group_gid | default(omit) }}"

- name: Configure SSH
  ansible.builtin.template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0600
    validate: /usr/sbin/sshd -t -f %s
    backup: true
  notify: Reload sshd

- name: Ensure SSH config directory exists
  ansible.builtin.file:
    path: /etc/ssh/sshd_config.d
    state: directory
    mode: 0755

- name: Add ssh users to ssh group
  ansible.builtin.user:
    name: "{{ item }}"
    groups: "{{ sshd_group_name }}"
    append: true
  loop: "{{ sshd_users }}"

- name: Setup UFW to allow SSH
  ansible.builtin.import_tasks:
    file: ufw.yml
