- name: Ensure OpenSSH server is installed
  ansible.builtin.package:
    name: openssh-server
    state: latest
  notify: Reload sshd

- name: Ensure SSH group exists
  ansible.builtin.group:
    name: "{{ ssh_group_name }}"
    gid: "{{ ssh_group_gid }}"

- name: Add ansible user to SSH group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: "{{ ssh_group_name }}"
    append: true

- name: Configure SSH
  ansible.builtin.template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0600
    validate: /usr/sbin/sshd -t -f %s
    backup: true
  notify: Reload sshd

- name: Ensure SSH config directory exists
  ansible.builtin.file:
    path: /etc/ssh/sshd_config.d
    state: directory
    mode: 0755

- name: Add ssh users to ssh group
  ansible.builtin.user:
    name: "{{ item }}"
    groups: "{{ ssh_group_name }}"
    append: true
  with_items: "{{ ssh_users }}"
  when: ssh_users

- name: Setup UFW to allow SSH
  ansible.builtin.import_tasks:
    file: ufw.yml
