- name: UFW allow SSH
  community.general.ufw:
    rule: limit
    port: "{{ ansible_port }}"
    proto: tcp
    direction: in
    from_ip: "{{ item }}"
    comment: SSH in
  with_items: "{{ ssh_from_ip }}"
