- name: UFW allow SSH in
  community.general.ufw:
    rule: limit
    port: "{{ sshd_port }}"
    proto: tcp
    direction: in
    from_ip: "{{ item }}"
    comment: SSH in
  with_items: "{{ sshd_from_ip }}"
