fail2ban_overalljails: "false"

fail2ban_ignoreips:
  - 127.0.0.1/8
  - ::1

fail2ban_bantime: 10m

fail2ban_findtime: 10m

fail2ban_maxretry: 5

fail2ban_loglevel: INFO

fail2ban_logtarget: SYSLOG  # /var/log/fail2ban.log

fail2ban_syslogsocket: auto

fail2ban_socket: /var/run/fail2ban/fail2ban.sock

fail2ban_pidfile: /var/run/fail2ban/fail2ban.pid

fail2ban_dbfile: /var/lib/fail2ban/fail2ban.sqlite3

fail2ban_dbpurgeage: 1d

fail2ban_dbmaxmatches: 10
